#set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'sainnhe/tmux-fzf'
#set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @vim_navigator_mapping_left "C-Left M-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right M-l"
set -g @vim_navigator_mapping_up "M-k"
set -g @vim_navigator_mapping_down "M-j"
set -g @vim_navigator_mapping_prev ""  
set -g mouse off
set -g default-terminal "tmux-256color"
set -g allow-passthrough on

unbind C-b
set-option -g prefix M-e
bind-key M-e send-prefix

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind M-w display-popup -h 90% -w 80% \
-E /home/kenpachi-zaraki/.config/scripts/navigation_scripts/fzf_tmux_window_navigation.sh "$HOME"
bind -n M-p display-popup -h 90% -w 80% \
-E /home/kenpachi-zaraki/.config/scripts/navigation_scripts/fzf_tmux_window_navigation.sh "$HOME/personal/"
bind M-q display-popup -h 90% -w 80% \
-E /home/kenpachi-zaraki/.config/scripts/navigation_scripts/fzf_tmux_window_navigation.sh "$HOME/.config"

set -as command-alias[100] 'create-window=display-popup -E /home/kenpachi-zaraki/.config/scripts/navigation_scripts/fzf_tmux_window_navigation.sh'

set -g base-index 1
set -g pane-base-index 1
set -g pane-border-style "fg=#c0caf5"
set -g pane-active-border-style "fg=#73daca"


set-window-option -g pane-base-index 1
set-option -g renumber-windows on

#set -g @plugin 'rose-pine/tmux'
#set -g @plugin 'wfxr/tmux-fzf-url'
#set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
#set -g @plugin 'alexwforsythe/tmux-which-key'
#set -g @plugin 'rickstaa/tmux-notify'
#set -g @plugin 'tmux-plugins/tmux-resurrect'
#set -g @plugin 'tmux-plugins/tmux-continuum'
#set -g @plugin 'tmux-plugins/tmux-battery'
#set -g @plugin 'omerxx/tmux-floax'
# set -g @plugin 'omerxx/tmux-sessionx'

set -g @continuum-restore 'on'
set -g @rose_pine_variant 'main' # Options are 'main', 'moon' or 'dawn'

set -g @floax-bind 'b'
set -g @floax-bind '-n C-x'
set -g @floax-text-color '#c0caf5'
set -g @floax-title '  pop-up '
set -g @floax-session-name 'session-private'
set -g @floax-change-path 'false'

set -g @rose_pine_user 'on'
set -g @rose_pine_host 'on'
set -g @rose_pine_date_time '%a %d %b %H:%M' # It accepts the date UNIX command format (man date for info)
set -g @rose_pine_directory 'off' # Turn on the current folder component in the status bar
set -g @rose_pine_bar_bg_disable 'on' # Disables background color, for transparent terminal emulators
set -g @rose_pine_bar_bg_disabled_color_option 'default'

# These are not padded
set -g @rose_pine_session_icon '' # Changes the default icon to the left of the session name
set -g @rose_pine_current_window_icon '' # Changes the default icon to the left of the active window name
set -g @rose_pine_folder_icon '' # Changes the default icon to the left of the current directory folder
set -g @rose_pine_username_icon '' # Changes the default icon to the right of the hostname
set -g @rose_pine_hostname_icon '󰒋 ' # Changes the default icon to the right of the hostname
set -g @rose_pine_date_time_icon '󰃰 ' # Changes the default icon to the right of the date module

set -g status-position bottom

#run '~/.tmux/plugins/tpm/tpm'
