{ config, pkgs, ...}: 

{
    environment.systemPackages = with pkgs; [
         python313
        python313Packages.pygame

        # Required libraries for pygame
        samba
        wakeonlan
	smbclient-ng
        zlib
        SDL2
        SDL2_image
        SDL2_mixer
        SDL2_ttf
        neovim
        wget
        htop
        yazi
        kitty
        rofi
        zsh
        tmux
        starship
        dunst
        fzf
        unzip
        wireguard-tools
        bat
        eza
        chromium
        git 
        fd 
        cliphist
        libnotify
        hypridle
        hyprlock
        hyprpaper
        hyprpicker
        swww
        nodejs
        rclone
        wl-clipboard 
        wtype
        grimblast
        swappy
        brightnessctl
        wireplumber
        whitesur-icon-theme
        tailscale
        ripgrep
        gcc 
        clang
        cmake 
        gnumake
        pkg-config
        binutils
        wireshark
        tcpdump
        bind
        mtr 
        iperf3 
        mariadb.client
        postgresql
        nmap
        gns3-server
        dynamips
        vpcs
        wireshark 
        ubridge
        python3
        python3Packages.pip 
        stdenv.cc.cc.lib 
        gns3-gui
        libreoffice
        tigervnc 
        nfs-utils 
        cloudflared 
        usbutils 
        fprintd 
        screen 
        rsyslog 
        vlc 
        vscode
        jdk
	linphone
        jetbrains.idea-oss
        spotify
        dnsmasq
        inetutils
	openiscsi
        ];

    }
